name: Daily YTMusic Scrobbling

on:
  schedule:
    # Runs at 12:00 UTC (adjust this time as needed)
    - cron: '0 12 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  scrobble:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv pip install --system ytmusicapi lastpy python-dotenv
    
    - name: Restore cache
      uses: actions/cache/restore@v3
      with:
        path: |
          data.db
          oauth.json
        key: ${{ runner.os }}-ytmusic-data
    
    - name: Create .env file
      run: |
        echo "LAST_FM_API=${{ secrets.LAST_FM_API }}" >> .env
        echo "LAST_FM_API_SECRET=${{ secrets.LAST_FM_API_SECRET }}" >> .env
        echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
        echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
        echo "LASTFM_SESSION=${{ secrets.LASTFM_SESSION }}" >> .env
    
    - name: Create oauth.json if not exists
      run: |
        if [ ! -f oauth.json ]; then
          echo '${{ secrets.OAUTH_JSON }}' > oauth.json
        fi
    
    - name: Run scrobbler
      run: python start.py
    
    - name: Save cache
      uses: actions/cache/save@v3
      with:
        path: |
          data.db
          oauth.json
        key: ${{ runner.os }}-ytmusic-data
